server:
  port: 8080
spring:
  application:
    name: "DNAMutant"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  redis:
    host: "localhost"
    port: 6379
springdoc:
  api-docs:
    groups:
      enabled: false
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: co.com.emorae.api
